import http from 'node:http';
import { readFile, writeFile, mkdir, readdir, stat } from 'node:fs/promises';
import { extname, join, resolve, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import crypto from 'node:crypto';
import { spawn } from 'node:child_process';

const root=fileURLToPath(new URL('.',import.meta.url));
const workspace=resolve(process.env.CRAZY_WORKSPACE||join(root,'workspace'));
const dataDir=resolve(process.env.CRAZY_DATA||join(root,'data'));
const memoryFile=join(dataDir,'memory.json'),auditFile=join(dataDir,'audit.jsonl');
const port=Number(process.env.PORT||3000), maxBody=2_000_000;
const modelProvider=(process.env.MODEL_PROVIDER||'auto').toLowerCase(),modelBase=process.env.MODEL_BASE_URL||'http://localhost:11434',modelName=process.env.MODEL_NAME||'qwen2.5:7b',apiKey=process.env.OPENAI_API_KEY||'';
const adminToken=process.env.CRAZY_ADMIN_TOKEN||'';
const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.svg':'image/svg+xml','.txt':'text/plain; charset=utf-8','.md':'text/markdown; charset=utf-8','.webmanifest':'application/manifest+json'};
await mkdir(workspace,{recursive:true}); await mkdir(dataDir,{recursive:true});
try{await readFile(memoryFile)}catch{await writeFile(memoryFile,JSON.stringify({shortTerm:[],projects:{},longTerm:[]},null,2))}
const rate=new Map();
function json(res,status,body,headers={}){res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','x-frame-options':'DENY','referrer-policy':'no-referrer','content-security-policy':"default-src 'self'; connect-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; script-src 'self'",...headers});res.end(JSON.stringify(body))}
function text(res,status,body,type='text/plain; charset=utf-8'){res.writeHead(status,{'content-type':type,'cache-control':'no-store','x-content-type-options':'nosniff','x-frame-options':'DENY','referrer-policy':'no-referrer','content-security-policy':"default-src 'self'; connect-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self'"});res.end(body)}
function id(){return crypto.randomUUID()}
function safePath(input){const target=resolve(workspace,String(input||'')),rel=relative(workspace,target);if(rel.startsWith('..')||rel.includes('..'+(process.platform==='win32'?'\\':'/')))throw new Error('Path outside Crazy Bot workspace');return target}
async function body(req){let raw='';for await(const c of req){raw+=c;if(raw.length>maxBody)throw new Error('Request too large')}return JSON.parse(raw||'{}')}
async function audit(action,meta={}){await writeFile(auditFile,JSON.stringify({id:id(),at:new Date().toISOString(),action,...meta})+'\n',{flag:'a'})}
async function loadMemory(){return JSON.parse(await readFile(memoryFile,'utf8'))} async function saveMemory(m){return writeFile(memoryFile,JSON.stringify(m,null,2))}
function allowed(req){if(!adminToken)return false;return req.headers.authorization===`Bearer ${adminToken}`}
function limited(req){const ip=req.headers['x-forwarded-for']||req.socket.remoteAddress||'unknown',now=Date.now(),x=rate.get(ip)||{at:now,n:0};if(now-x.at>60000){x.at=now;x.n=0}x.n++;rate.set(ip,x);return x.n>60}
const agents={orchestrator:'Routes intent and coordinates agents.',reasoning:'Breaks problems into assumptions and decisions.',critic:'Finds risks and weak assumptions.',creative:'Generates alternatives.',coding:'Designs implementation and tests.',research:'Structures research and evidence.',planning:'Turns goals into executable plans.',voice:'Coordinates speech interaction.',memory:'Manages explicit memory.'};
function route(mode,message){if(mode==='code'||/\b(code|build|debug|bug|api|program|website|app)\b/i.test(message))return['orchestrator','coding','critic'];if(mode==='research')return['orchestrator','research','critic'];if(mode==='plan')return['orchestrator','planning','critic'];if(mode==='create')return['orchestrator','creative','critic'];return['orchestrator','reasoning','critic']}
function fallback(message,mode,execution){return`I routed this through ${execution.slice(1).join(' + ')}.\n\nGOAL\n${message}\n\nNEXT MOVE\nDefine the smallest testable version, its success metric, and one concrete action now.${mode==='crazy'?'\n\nCHALLENGE\nWhat assumption would make this fail? Who has the problem badly enough to act? What is the fastest experiment that could disprove it?':''}`}
async function modelChat(messages){const provider=modelProvider==='auto'?(apiKey?'openai':'ollama'):modelProvider;if(provider==='none')return null;if(provider==='openai'&&apiKey){const r=await fetch((process.env.OPENAI_BASE_URL||'https://api.openai.com/v1')+'/chat/completions',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${apiKey}`},body:JSON.stringify({model:process.env.OPENAI_MODEL||'gpt-5-mini',messages,temperature:.4})});if(!r.ok)throw Error(`Model provider returned ${r.status}`);return(await r.json()).choices?.[0]?.message?.content||null}if(provider==='ollama'){const r=await fetch(modelBase.replace(/\/$/,'')+'/api/chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({model:modelName,messages,stream:false})});if(!r.ok)throw Error(`Local model returned ${r.status}`);return(await r.json()).message?.content||null}return null}
async function chat(input){const message=String(input.message||'').trim();if(!message)throw Error('Message is required.');const mode=String(input.mode||'crazy').toLowerCase(),execution=route(mode,message),memory=await loadMemory();let response=null,provider='fallback';try{response=await modelChat([{role:'system',content:`You are Crazy Bot. Encourage the person, challenge the idea, build the solution. Mode=${mode}. Agents=${execution.join(', ')}. Be practical and concise.`},{role:'user',content:message}]);if(response)provider=modelProvider==='auto'?(apiKey?'openai':'ollama'):modelProvider}catch(e){await audit('model_error',{error:e.message})}if(!response)response=fallback(message,mode,execution);memory.shortTerm.push({role:'user',content:message,at:new Date().toISOString()},{role:'assistant',content:response,at:new Date().toISOString()});memory.shortTerm=memory.shortTerm.slice(-40);await saveMemory(memory);await audit('chat',{mode,execution,provider});return{ok:true,id:id(),mode,execution,provider,response,steps:['Understand','Challenge','Explore','Compare','Score','Improve','Execute']}}
async function listFiles(dir=''){const base=safePath(dir),entries=await readdir(base,{withFileTypes:true});return Promise.all(entries.filter(e=>!e.name.startsWith('.')).map(async e=>{const p=join(base,e.name),s=await stat(p);return{name:e.name,type:e.isDirectory()?'directory':'file',size:s.size,modified:s.mtime.toISOString(),path:relative(workspace,p)}}))}
function runAllowed(command,args=[],cwd=workspace){return new Promise((resolveRun,reject)=>{const allowedCmd=['node','npm','git'];if(!allowedCmd.includes(command))return reject(Error('Command not allowlisted'));const child=spawn(command,args,{cwd:safePath(relative(workspace,resolve(cwd))),shell:false,env:{...process.env,PATH:process.env.PATH,NODE_OPTIONS:'--max-old-space-size=512'}});let out='',err='';const timer=setTimeout(()=>{child.kill('SIGKILL');reject(Error('Command timed out'))},15000);child.stdout.on('data',d=>{out+=d.toString().slice(0,20000)});child.stderr.on('data',d=>{err+=d.toString().slice(0,20000)});child.on('error',e=>{clearTimeout(timer);reject(e)});child.on('close',code=>{clearTimeout(timer);resolveRun({code,stdout:out,stderr:err})})})}
const server=http.createServer(async(req,res)=>{try{if(limited(req))return json(res,429,{ok:false,error:'Rate limit exceeded'});const url=new URL(req.url,'http://localhost');
if(req.method==='GET'&&url.pathname==='/health')return json(res,200,{ok:true,service:'crazy-bot',status:'healthy',uptime:process.uptime(),version:'3.0.0'});
if(req.method==='GET'&&url.pathname==='/api/status')return json(res,200,{ok:true,local:true,network:!!apiKey,provider:modelProvider,model:modelProvider==='ollama'?modelName:(process.env.OPENAI_MODEL||'not configured'),agents:Object.keys(agents),developerMode:allowed(req),voice:true,pwa:true,version:'3.0.0'});
if(req.method==='GET'&&url.pathname==='/api/memory')return json(res,200,await loadMemory());
if(req.method==='POST'&&url.pathname==='/api/chat')return json(res,200,await chat(await body(req)));
if(req.method==='POST'&&url.pathname==='/api/memory'){const b=await body(req),m=await loadMemory(),item={id:id(),text:String(b.text||'').slice(0,5000),project:String(b.project||'default'),at:new Date().toISOString()};m.longTerm.push(item);await saveMemory(m);await audit('memory_add',{memoryId:item.id});return json(res,201,{ok:true,item})}
if(req.method==='DELETE'&&url.pathname.startsWith('/api/memory/')){const mid=url.pathname.split('/').pop(),m=await loadMemory();m.longTerm=m.longTerm.filter(x=>x.id!==mid);await saveMemory(m);await audit('memory_delete',{memoryId:mid});return json(res,200,{ok:true})}
if(req.method==='GET'&&url.pathname==='/api/files')return json(res,200,{ok:true,files:await listFiles(url.searchParams.get('path')||'')});
if(req.method==='GET'&&url.pathname==='/api/file'){const p=safePath(url.searchParams.get('path'));if(!(await stat(p)).isFile())throw Error('Not a file');return text(res,200,await readFile(p,'utf8'))}
if(req.method==='POST'&&url.pathname==='/api/file'){if(!allowed(req))return json(res,403,{ok:false,error:'Developer token required for file writes'});const b=await body(req),p=safePath(b.path),rel=relative(workspace,p);if(!rel||rel.startsWith('..'))throw Error('Invalid path');await mkdir(resolve(p,'..'),{recursive:true});await writeFile(p,String(b.content||''));await audit('file_write',{path:rel});return json(res,201,{ok:true,path:rel})}
if(req.method==='GET'&&url.pathname==='/api/dev/diagnostics'){if(!allowed(req))return json(res,403,{ok:false,error:'Developer token required'});const checks=[];for(const [c,a] of [['node',['--version']],['npm',['--version']],['git',['--version']]]){try{checks.push({command:c,result:await runAllowed(c,a)})}catch(e){checks.push({command:c,error:e.message})}}return json(res,200,{ok:true,workspace,checks,git:await runAllowed('git',['status','--short'])})}
if(req.method==='POST'&&url.pathname==='/api/dev/command'){if(!allowed(req))return json(res,403,{ok:false,error:'Developer token required'});const b=await body(req),cmd=String(b.command||'');const args=Array.isArray(b.args)?b.args.map(String).slice(0,20):[];const result=await runAllowed(cmd,args,b.cwd||workspace);await audit('developer_command',{command:cmd,args});return json(res,200,{ok:true,result})}
if(req.method==='GET'&&url.pathname==='/api/audit'){if(!allowed(req))return json(res,403,{ok:false,error:'Developer token required'});let data='';try{data=await readFile(auditFile,'utf8')}catch{}return text(res,200,data,'text/plain; charset=utf-8')}
if(req.method==='GET'){const path=url.pathname==='/'?'/index.html':url.pathname,safe=path.replace(/\.\./g,''),file=join(root,'public',safe);try{return text(res,200,await readFile(file),mime[extname(file)]||'application/octet-stream')}catch{return json(res,404,{error:'Not found'})}}
return json(res,405,{error:'Method not allowed'})
}catch(e){await audit('error',{error:e.message});return json(res,400,{ok:false,error:e.message})}});
server.listen(port,'0.0.0.0',()=>console.log(`Crazy Bot listening on ${port}`));
